### PR TITLE
Use babel to compile JS

### PR DESCRIPTION
**Pull request by arianahl**
This will give a head start by compiling the JS with Babel but I think that in the future if tests, minifiers and other building stuff are going to be added to the project then a build system like Gulp or Grunt should be used instead of NPM scripts.

- Moved raw files into 'src' directory
- Compiled files are outputted in 'bld' directory
- Copied views and static files into the 'bld' directory
- Updated app.js to find the views in the correct directory
- Updated gitignore and package json 

#14

### CODE REVIEW

**Comment by connorphee** [comment]
@arianahl thank you very much for the ton of help. I absolutely agree a build system is necessary. This is all stuff I have been thinking of, but with the time taken up by classes I have not gotten to. I am replying from my phone, so I will check this out more when I get to my computer later! Thanks again!

**Comment by connorphee** [comment]
@arianahl I am looking over this and it looks like you removed the local strategy import but it is still being used later in app.js, which is throwing an error. It is possible I am missing something, are you getting the same error?

**Comment by arianahl** [comment]
Oh sorry @connorphee I was working with #13 and I must have committed the line in the wrong branch. I will remove it from here and get it into the login one.

**Comment by connorphee** [comment]
@arianahl no big deal, just wanted to double check!

**Comment by connorphee** [comment]
@arianahl as a heads up, I pulled in your branch and everything looks great! It you don't mind I am going to work on that branch to update code to pass eslint and I will push it back up for you to look at before I merge.

**Comment by arianahl** [comment]
Ok, sounds good!

**Comment by connorphee** [comment]
@arianahl I pushed your branch back up with updated code. There are a few lines I cannot get to both pass eslint and not fail the build. If you have any ideas on how to fix them feel free! Let me know what you think!

**Comment by arianahl** [comment]
@connorphee I fixed the last issues. 
I removed all the 'eslint ignores' and the imports 'default as' since they weren't necessary.
All seems working and eslint is happy, let me know what you think.

**Comment by connorphee** [comment]
I think this looks really good! Thank you so much for the help! If you would like to contribute more please let me know! Merging.

**Comment by arianahl** [comment]
I'm happy to help. Let me know what would you like me to tackle next.

**Pull request merged**
