### PR TITLE
Allow login by email

### LINKED ISSUE #1: Modify user creation/login to rely on user email
Currently user creation and login relies a user-defined username. This will be problematic for another issue, resetting passwords. While it is possible to use another method for password reset such as security questions, email seems to be a necessity.

Refactoring needs to be done for the creation and login of users, as well as the userSchema itself.

### PR DESCRIPTION
**Pull request by arianahl**
Added email to model and view. Username and email are validated to not be already in the DB with a logic-or.
Validation message is the same for username and email when not unique for security purposes but it could be separated.

Resolves #1

### CODE REVIEW

**Comment by connorphee** [comment]
Thank you for this @arianahl ! I will take a look at this tonight when I get a chance, will let you know what I think!

**Comment by connorphee** [comment]
@arianahl just pulled your branch down and reviewing/solving conflicts. Sorry for delay, classwork has kept me busy. Will comment back soon.

**Comment by connorphee** [comment]
@arianahl I have pushed up your branch in this repo. Because files had moved to src/ I had to put your changes back in. I also made some minor additions, adding the required tag to all fields in registration, adding a first and last name field, and adding an eslint rule to prevent it from failing when you use `this` in the saving of a user. The only other thing I could think of would be an issue where usernames are case sensitive. I am curious what your opinion and any possible solutions you might have for this. For example, as it is now, someone could have the username `name` and a new user could register with the username `Name`. I'm not sure if that is a good thing or bad. Let me know what you think.

**Comment by arianahl** [comment]
Hi @connorphee, in that case, I would use the mongoose-unique-validator plugin to validate uniqueness and doing it with case insensitivity for both username and email. That means all the validation code I wrote could be removed and we ensure validation and unique values in one go. I can add a commit to this branch or I could make a new pull request, whichever is easier for you.

**Comment by arianahl** [comment]
I added the changes for validation at creation time but if you want to allow login to be also case insensitive then a small modification to the findUsername function has to be made. 
I'm not sure if case insensitivity should be allowed in the login page... what do you think?

**Comment by connorphee** [comment]
@arianahl Thanks so much! I am not quite sure if we should allow case insensitivity at login. I definitely don't think we should allow the case I mentioned above at registration though. I will leave it up to you to decide for now and we will see how it looks!

**Comment by arianahl** [comment]
@connorphee I added new commits to this branch for the registration case and left the login to be case sensitive. Plz check it out and let me know

**Comment by connorphee** [comment]
I pulled down the new changes, but `npm start` got stuck on `node ./bld/app.js` for almost an hour and I'm not sure why.

**Comment by arianahl** [comment]
Mine works fine and I merged everything from master....
It uses a new module. Did you do npm install before? 
And maybe the database is in a bad state? I would first drop it and then try it again.

**Comment by connorphee** [comment]
@arianahl I'm not quite sure what the problem is. I have spent the last 90 minutes or so trying to figure out why it hangs up on `node ./bld/app.js`. I hope to figure it out because I think this branch is ready to be merged but I would like to see it working locally first.

**Comment by connorphee** [comment]
Figured it out, branch looks good. Merging.

**Pull request merged**
