### PR TITLE
Reset password proposal #2

### PR DESCRIPTION
**Pull request by wildan3105**
Hi, this is a mayor update. Everything works except one : how to hash and salt new password ? Maybe need different issue

- [x] Require email to register
- [x] Create reset password at login page
- [x] Generate random string as new password
- [x] Send reset password link and new password via e-mail
- [ ] How to hash and salt new password?

And one more, maybe user can change password after login due to random password generated by this issue is hard to remember. I will wait your review about this. Thanks

### CODE REVIEW

**Comment by connorphee** [comment]
@wildan3105 going to check this out now! Will get back to you soon!

**Comment by connorphee** [comment]
@wildan3105 I am getting an error when attempting to send a reset email

> smtp: '454 4.7.0 Too many login attempts, please try again later

Are you seeing this as well? As for the hashing and salting a new password, I will have to look into it more. I somewhat am regretting using the passport stack for auth, as it has caused me some trouble as well.

**Comment by wildan3105** [comment]
No, try this configuration (in my case I use gmail) : 
```
server = email.server.connect({
    user: 'username@gmail.com',
    password: 'password',
    host: 'smtp.gmail.com',
    ssl: true
});
```
> I am getting an error when attempting to send a reset email

Yeah, you better do that. I myself used `simply-encryptor` to encrypt user's password.
> I will have to look into it more. I somewhat am regretting using the passport stack for auth, as it has caused me some trouble as well.

Please notify me if anything wrong, so far everything works except the hash and salt

**Comment by connorphee** [comment]
Yes I am looking into the salt/hash issue, but your PR looks great and I will merge it once I solve the other issue!

**Comment by connorphee** [comment]
@wildan3105 I'm sorry I am just getting to this in depth. Classwork has been very heavy since midterms are approaching. Could you explain the flow of the reset link and reset pass, or what they are meant to do exactly?

**Pull request closed without merging**
